name: Convooy
options:
  bundleIdPrefix: com.cassette
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  Convooy:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cassette.convooy
        INFOPLIST_FILE: Sources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # MapBox configuration
        MAPBOX_ACCESS_TOKEN: "$(MAPBOX_ACCESS_TOKEN)"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Convooy
        CFBundleIdentifier: com.cassette.convooy
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        # Location permissions
        NSLocationWhenInUseUsageDescription: "This app needs location access to show your current location and plan trips."
        NSLocationAlwaysAndWhenInUseUsageDescription: "This app needs location access to show your current location and plan trips."
        NSLocationAlwaysUsageDescription: "This app needs location access to show your current location and plan trips."
        # MapBox permissions
        NSLocationTemporaryUsageDescriptionDictionary:
          ShowCurrentLocation: "This app needs location access to show your current location on the map."
        # Required for MapBox
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        # MapBox access token (will be set via environment variable)
        MAPBOX_ACCESS_TOKEN: "$(MAPBOX_ACCESS_TOKEN)"

schemes:
  Convooy:
    build:
      targets:
        Convooy: all
    run:
      config: Debug
      environmentVariables:
        MAPBOX_ACCESS_TOKEN: "$(MAPBOX_ACCESS_TOKEN)"
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 