name: Backend Tests

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: convooy_test
          POSTGRES_USER: convooy_user
          POSTGRES_PASSWORD: convooy_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: backend/yarn.lock
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Generate Prisma Client
        run: yarn db:generate
      
      - name: Push database schema
        run: yarn db:push
        env:
          DATABASE_URL: postgresql://convooy_user:convooy_password@localhost:5432/convooy_test
      
      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://convooy_user:convooy_password@localhost:5432/convooy_test
          CI: true

